version: "3"

services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./www:/var/www/${PROJECT_NAME}:delegated
      - ./docker/php/conf/custom-bx-php.ini:/usr/local/etc/php/conf.d/custom-bx-php.ini
    depends_on:
      - mariadb
      - web_server
    restart: always
    env_file:
      - .env

  web_server:
    build: docker/${SERVER_TYPE}
    volumes:
      - ./www:/var/www/${PROJECT_NAME}:delegated
    ports:
      - ${SERVER_PORT}:80
    env_file:
      - .env
    restart: always

  mariadb:
    image: mariadb:latest
    volumes:
      - db:/var/lib/mysql
      - ./docker/mariadb/conf:/etc/mysql/conf.d
    env_file:
      - .env
    depends_on:
      - web_server
    restart: always

  memcached:
    image: memcached:latest
    depends_on:
      - web_server
      - php
    restart: always

volumes:
  db:
